sudo: required
language: generic

services:
    - docker

before install:
    - docker build -t shivamgoyal312/react-test -f ./client/Dockerfile.dev ./client

script: 
    - docker run -e CI=true shivamgoyal312/react-test npm test

after_success:
    - docker build -t shivamgoyal312/multi-client ./client
    - docker build -t shivamgoyal312/multi-nginx ./nginx
    - docker build -t shivamgoyal312/multi-server ./server
    - docker build -t shivamgoyal312/multi-worker ./worker
    #Docker LOGIN
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #PUsh images to Docker Hub
    - docker push shivamgoyal312/multi-client
    - docker push shivamgoyal312/multi-nginx
    - docker push shivamgoyal312/multi-server
    - docker push shivamgoyal312/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker 
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-817266766173
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY